### test connection
GET http://localhost:8080/

### get all todos
GET http://localhost:8080/todos

### get single todo
GET http://localhost:8080/todo/2


### create a new todo
POST http://localhost:8080/todo
Content-Type: application/json

 {
    "ID": "4",
    "Todo": "Sit and relax.",
    "Done": false
}